spring:
  main:
    banner-mode: off
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:///C://Users//Brandon//Documents//config"

server:
  port: 8071