server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  main:
    banner-mode: "off"
logging:
  level:
    root: OFF
    com.brandon: INFO

build:
  version: "1.0"

accounts:
  message: "Welcome to Browns Banks accounts related local APIs"
  contactDetails:
    name: "Bandon Gandon - Developer"
    email: "bandon@gandon.com"
  onCallSupport:
    - (333) 123-1234
    - (333) 324-1345