spring:
  application:
    name: "configserver"
  profiles:
    active: "native"
  cloud:
    config:
      server:
        native:
          # search-locations: "classpath:/config"
          search-locations: "file:///C://Users//Brandon//Documents//GitHub//Spring-Microservices-Training//configserver//src//main//resources//config"
server:
  port: 8071
